import React from 'react'

export const metadata = {
    title: 'order',
    description: 'Generated by create next app',
  }
  

function order() {
  return (
    <div>order</div>
  )
}

export default order